#!/bin/bash

if [ "$1" == "--help" ]; then
  echo "Usage: $0 <directory> <command>"
  echo "Monitors a directory for changes and executes a command when changes are detected."
  exit 0
fi

DIR_TO_WATCH=${1}
COMMAND=${2}
 
trap "echo Exited!; exit;" SIGINT SIGTERM
while : 
do
  watch --chgexit -n 1 "ls -ltr --recursive --full-time ${DIR_TO_WATCH} | sha256sum" && ${COMMAND}
  sleep 1
done
